sudo: required
services:
   - docker

before_install: 
   - docker build -t cmcklveen/frontend -f Dockerfile.dev  .

script:
   - docker run -e CI=true -t cmcklveen/frontend npm run test -- --coverage